### ISSUE TITLE
RAILS_ENV not always set

### ISSUE THREAD

**Issue by lassebunk** [opbeat/opbeat_ruby#15]
In Rails applications, the `ENV['RAILS_ENV']` environment variable is not always set, e.g. in development when using [Pow](http://pow.cx/) as the development server. This causes `current_environment` to be set to `"default"` even though the environment is development.

[This line](https://github.com/opbeat/opbeat_ruby/blob/master/lib/opbeat/configuration.rb#L54) could be changed to:

```ruby
self.current_environment = (defined?(Rails) && Rails.env) || ENV['RACK_ENV'] || 'default'
```

And it would work in all Rails environments.

Thanks.

**Comment by watson** [comment]
This have now been fixed in 92daa98 - it will be released on rubygems shortly
