### ISSUE TITLE
no superclass method `assert_required_properties_set!' for Opbeat::ExceptionInterface

### ISSUE THREAD

**Issue by olleolleolle** [opbeat/opbeat_ruby#16]
I got this problem from using Hashie which is a part of the Grape API framework.

```
NoMethodError at /alive.json
  
super: no superclass method `assert_required_properties_set!' for #<Opbeat::ExceptionInterface:0x007f8d52060040>

Ruby	
      
/Users/olle/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/opbeat-0.5.2/lib/opbeat/interfaces.rb
: in 
assert_required_properties_set!
```

This part of the raven-like ecosystem seems to have solved this problem: https://github.com/getsentry/raven-ruby/pull/191/files

**Comment by watson** [comment]
@olleolleolle We stopped using hashie in version 0.9.2 of the Ruby agent - forgot to close this issue back then
