### ISSUE TITLE
Use `Rails.application.config.filter_parameters` when possible

### ISSUE THREAD

**Issue by roncohen** [opbeat/opbeat_ruby#20]
The agent should adhere to `Rails.application.config.filter_parameters` when possible. We already have a way to filter sensitive data, but Rails users will be more familiar with this approach. 

It might be worth simplifying the filter mechanism while we're at it. I'm thinking a simple list of regexes that are recursively matched against the hash and the data is removed if the key maches a regex?

**Comment by Christian-Hansen** [comment]
:+1: - In the meantime an example of filtering out `arbitrary_param_name`

**Comment by watson** [comment]
This have finally been implemented in the newly released v2.0 of the Ruby agent. It will detect a Rails installation and use the Rails settings OR you can overwrite these manually for Opbeat. If not running Rails, Opbeat will fall back to sensible default filters of cause :)
