### ISSUE TITLE
Support sending information to the Opbeat servers from a separate thread

### ISSUE THREAD

**Issue by roncohen** [opbeat/opbeat_ruby#21]
It would be useful for the agent to be able to delegate the actual sending to a background thread. That would enable us to increase the open_timeout and read_timeout without significantly affecting performance.

**Comment by watson** [comment]
Since v0.9.2 it's now possible to communicate with the Opbeat API using a background job or another thread. This way you can increase the timeouts without worrying that this holds up any ongoing client request: https://github.com/opbeat/opbeat_ruby#async-delivery
