### ISSUE TITLE
Send user agent that tells Opbeat that this is Ruby

### ISSUE THREAD

**Issue by roncohen** [opbeat/opbeat_ruby#22]
We should change the user agent to follow the convention started by the node agent (`opbeat-nodejs/version`). Today it just looks like: (`opbeat/version`). Ideally. we'd include the framework too, e.g.: `opbeat-ruby/version; rails/4.2` if the rails integration is in effect.

**Comment by watson** [comment]
In master 3133cb4b64b86c2b60c1925c5207b84455744bfd the user-agent is now called `upbeat-ruby/version`. Good idea about adding `rails/version` as well - I'll see what I can do.

**Comment by watson** [comment]
I think the rails version is better logged under the "extra" pane for each error. I've added that + the Ruby version as well in 5f33bbc1e009268bc0e63a7f4e94b36e958873c9
