### ISSUE TITLE
current user not showing in Opbeat

### ISSUE THREAD

**Issue by jpalumickas** [opbeat/opbeat_ruby#26]
Hey,

We're using Devise gem and there is a `current_user` method in controller, but I cannot see any information about user in Opbeat error page.

**Comment by roncohen** [comment]
Hey,

Sorry for the slow reply. Let me know what your organization is called on Opbeat and I can take a look.

/Ron

**Comment by jpalumickas** [comment]
Hey,

Sent an email to you
